# Homework 1

### Environment Description 

In [32]:
import numpy as np

P = np.array([[0.4, 0.4, 0.2, 0.0],
              [0.2, 0.5, 0.2, 0.1],
              [0.1, 0.4, 0.4, 0.1],
              [0.0, 0.5, 0.1, 0.4]])

v0 = np.array([1, 0, 0, 0])

### State Distribution

1. Calculate the state distribution at t=2

In [33]:
P2 = np.linalg.matrix_power(P, 2)

print(f"P^2 = {P2}")

v2 = v0.dot(P2)

print(f"State distribution at t=2: {v2}")

P^2 = [[0.26 0.44 0.24 0.06]
 [0.2  0.46 0.23 0.11]
 [0.16 0.45 0.27 0.12]
 [0.11 0.49 0.18 0.22]]
State distribution at t=2: [0.26 0.44 0.24 0.06]


2. What is the probability that the System is in Blackout state (S4) at t=10?

In [34]:
P10 = np.linalg.matrix_power(P, 10)

print(f"P^10 = {P10}")

v10 = v0.dot(P10)

print(f"State distribution at t=10: {v10}")

print(f"Probability of System being in S4 at t=10: {v10[3]}")

P^10 = [[0.19171131 0.45726372 0.23558286 0.11544212]
 [0.19168919 0.45727342 0.23556793 0.11546946]
 [0.19167677 0.45727864 0.23556022 0.11548438]
 [0.19164943 0.45729105 0.2355406  0.11551892]]
State distribution at t=10: [0.19171131 0.45726372 0.23558286 0.11544212]
Probability of System being in S4 at t=10: 0.1154421180000001


3. Is there a stationary distribution?

In [35]:
# Initial Case

t = 100000

v = v0.dot(np.linalg.matrix_power(P, t))

print(f"State distribution: {v}")

State distribution: [0.19168591 0.45727483 0.23556582 0.11547344]


In [36]:
# Case with sink state

P_sink = np.array([[0.4, 0.4, 0.2, 0.0, 0.0],
                   [0.2, 0.5, 0.2, 0.1, 0.0],
                   [0.1, 0.4, 0.4, 0.1, 0.0],
                   [0.0, 0.1, 0.02, 0.08, 0.8],
                   [0.0, 0.0, 0.0, 0.0, 1.0]])

v0 = np.array([1, 0, 0, 0, 0])

t = 100000

v = v0.dot(np.linalg.matrix_power(P_sink, t))

print(f"State distribution: {v}")

State distribution: [0. 0. 0. 0. 1.]


In [47]:
# Case with new slow regime

P_new = np.array([[0.4, 0.4, 0.2, 0.0],
                  [0.1, 0.6, 0.2, 0.1],
                  [0.05, 0.4, 0.45, 0.1],
                  [0.0, 0.25, 0.05, 0.7]])

v0 = np.array([1, 0, 0, 0])

t = 100000

v = v0.dot(np.linalg.matrix_power(P_new, t))

print(f"State distribution: {v}")

State distribution: [0.09471095 0.45756458 0.22140221 0.22632226]
